namespace ServiceLib.Common;

/// <summary>
/// JSON serialization context for Native AOT support
/// Add your types here to enable AOT-friendly JSON serialization
/// </summary>
[JsonSourceGenerationOptions(
    WriteIndented = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNameCaseInsensitive = true,
    ReadCommentHandling = JsonCommentHandling.Skip)]
// Core Models
[JsonSerializable(typeof(Config))]
[JsonSerializable(typeof(ProfileItem))]
[JsonSerializable(typeof(ProfileItemModel))]
[JsonSerializable(typeof(RoutingItem))]
[JsonSerializable(typeof(SubItem))]
[JsonSerializable(typeof(DNSItem))]
[JsonSerializable(typeof(RulesItem))]
[JsonSerializable(typeof(GitHubRelease))]
[JsonSerializable(typeof(V2rayMetricsVarsStats))]
[JsonSerializable(typeof(V2rayMetricsVarsLink))]
[JsonSerializable(typeof(TrafficItem))]
[JsonSerializable(typeof(ClashProxies))]
[JsonSerializable(typeof(ClashProviders))]
// List types
[JsonSerializable(typeof(List<ProfileItem>))]
[JsonSerializable(typeof(List<ProfileItemModel>))]
[JsonSerializable(typeof(List<RoutingItem>))]
[JsonSerializable(typeof(List<SubItem>))]
[JsonSerializable(typeof(List<DNSItem>))]
[JsonSerializable(typeof(List<RulesItem>))]
[JsonSerializable(typeof(List<GitHubRelease>))]
// Singbox models
[JsonSerializable(typeof(SingboxConfig))]
[JsonSerializable(typeof(Log4Sbox))]
[JsonSerializable(typeof(Dns4Sbox))]
[JsonSerializable(typeof(Server4Sbox))]
[JsonSerializable(typeof(List<Server4Sbox>))]
[JsonSerializable(typeof(Inbound4Sbox))]
[JsonSerializable(typeof(List<Inbound4Sbox>))]
[JsonSerializable(typeof(Outbound4Sbox))]
[JsonSerializable(typeof(List<Outbound4Sbox>))]
[JsonSerializable(typeof(Endpoints4Sbox))]
[JsonSerializable(typeof(List<Endpoints4Sbox>))]
[JsonSerializable(typeof(Route4Sbox))]
[JsonSerializable(typeof(Rule4Sbox))]
[JsonSerializable(typeof(List<Rule4Sbox>))]
[JsonSerializable(typeof(Ruleset4Sbox))]
[JsonSerializable(typeof(List<Ruleset4Sbox>))]
[JsonSerializable(typeof(User4Sbox))]
[JsonSerializable(typeof(List<User4Sbox>))]
[JsonSerializable(typeof(Peer4Sbox))]
[JsonSerializable(typeof(List<Peer4Sbox>))]
[JsonSerializable(typeof(Tls4Sbox))]
[JsonSerializable(typeof(Multiplex4Sbox))]
[JsonSerializable(typeof(Utls4Sbox))]
[JsonSerializable(typeof(Reality4Sbox))]
[JsonSerializable(typeof(Transport4Sbox))]
[JsonSerializable(typeof(Headers4Sbox))]
[JsonSerializable(typeof(HyObfs4Sbox))]
[JsonSerializable(typeof(Experimental4Sbox))]
[JsonSerializable(typeof(CacheFile4Sbox))]
[JsonSerializable(typeof(V2ray_Api4Sbox))]
[JsonSerializable(typeof(Clash_Api4Sbox))]
[JsonSerializable(typeof(Stats4Sbox))]
// V2Ray models - Main config
[JsonSerializable(typeof(V2rayConfig))]
[JsonSerializable(typeof(Log4Ray))]
[JsonSerializable(typeof(Dns4Ray))]
[JsonSerializable(typeof(DnsServer4Ray))]
[JsonSerializable(typeof(List<DnsServer4Ray>))]
[JsonSerializable(typeof(Inbounds4Ray))]
[JsonSerializable(typeof(List<Inbounds4Ray>))]
[JsonSerializable(typeof(Outbounds4Ray))]
[JsonSerializable(typeof(List<Outbounds4Ray>))]
[JsonSerializable(typeof(Routing4Ray))]
[JsonSerializable(typeof(Metrics4Ray))]
[JsonSerializable(typeof(Policy4Ray))]
[JsonSerializable(typeof(Stats4Ray))]
[JsonSerializable(typeof(Observatory4Ray))]
[JsonSerializable(typeof(BurstObservatory4Ray))]
[JsonSerializable(typeof(BurstObservatoryPingConfig4Ray))]
// V2Ray models - Detailed types
[JsonSerializable(typeof(SystemPolicy4Ray))]
[JsonSerializable(typeof(Sniffing4Ray))]
[JsonSerializable(typeof(Inboundsettings4Ray))]
[JsonSerializable(typeof(UsersItem4Ray))]
[JsonSerializable(typeof(List<UsersItem4Ray>))]
[JsonSerializable(typeof(AccountsItem4Ray))]
[JsonSerializable(typeof(List<AccountsItem4Ray>))]
[JsonSerializable(typeof(Outboundsettings4Ray))]
[JsonSerializable(typeof(VnextItem4Ray))]
[JsonSerializable(typeof(List<VnextItem4Ray>))]
[JsonSerializable(typeof(ServersItem4Ray))]
[JsonSerializable(typeof(List<ServersItem4Ray>))]
[JsonSerializable(typeof(SocksUsersItem4Ray))]
[JsonSerializable(typeof(List<SocksUsersItem4Ray>))]
[JsonSerializable(typeof(Mux4Ray))]
[JsonSerializable(typeof(Response4Ray))]
[JsonSerializable(typeof(FragmentItem4Ray))]
[JsonSerializable(typeof(WireguardPeer4Ray))]
[JsonSerializable(typeof(List<WireguardPeer4Ray>))]
// V2Ray models - Stream settings
[JsonSerializable(typeof(StreamSettings4Ray))]
[JsonSerializable(typeof(TlsSettings4Ray))]
[JsonSerializable(typeof(TcpSettings4Ray))]
[JsonSerializable(typeof(Header4Ray))]
[JsonSerializable(typeof(KcpSettings4Ray))]
[JsonSerializable(typeof(WsSettings4Ray))]
[JsonSerializable(typeof(Headers4Ray))]
[JsonSerializable(typeof(HttpupgradeSettings4Ray))]
[JsonSerializable(typeof(XhttpSettings4Ray))]
[JsonSerializable(typeof(HttpSettings4Ray))]
[JsonSerializable(typeof(QuicSettings4Ray))]
[JsonSerializable(typeof(GrpcSettings4Ray))]
[JsonSerializable(typeof(Sockopt4Ray))]
// V2Ray models - Routing
[JsonSerializable(typeof(RulesItem4Ray))]
[JsonSerializable(typeof(List<RulesItem4Ray>))]
[JsonSerializable(typeof(BalancersItem4Ray))]
[JsonSerializable(typeof(List<BalancersItem4Ray>))]
[JsonSerializable(typeof(BalancersStrategy4Ray))]
[JsonSerializable(typeof(BalancersStrategySettings4Ray))]
[JsonSerializable(typeof(BalancersStrategySettingsCosts4Ray))]
[JsonSerializable(typeof(List<BalancersStrategySettingsCosts4Ray>))]
// Common types
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(bool))]
public partial class AotJsonContext : JsonSerializerContext
{
}
